--- pyproject.toml.orig	2023-05-26 23:37:18 UTC
+++ pyproject.toml
@@ -15,7 +15,7 @@ classifiers = [
 [tool.poetry.dependencies]
 python = "^3.7"
 poetry = "^1.5"
-tomlkit = "^0.11.4"
+tomlkit = ">=0.11.4,<0.13.0"
 packaging = ">=21.3,<24.0"
 
 [tool.poetry.group.dev.dependencies]
